-- ==================================================================
-- Views are now managed by dbt (see dbt/ directory).
-- ==================================================================
--
-- Run `docker compose -f compose/docker-compose.yml --profile dbt run dbt`
-- to create/update all views via dbt.
--
-- The original SQL is preserved in 020-views.sql.replaced-by-dbt
-- for reference during the migration period.
--
-- GRANTs are handled by dbt's on-run-end hook
-- (see dbt/macros/grant_select_to_vlc_dev.sql).
-- ==================================================================
