-- ==================================================================
-- To be populated once in need of later-phase presentation views
-- that should not mix into the core hypertable/cagg bootstrap.
-- ==================================================================