-- ==================================================================
-- To be populated once in need of “presentation layer” views
-- that should not mix into the core hypertable/cagg bootstrap.
-- ==================================================================