#!/usr/bin/env bash
#
# sync-dev-secrets.sh - Generate local dev secrets from .env
#
# This script derives secrets (htpasswd, JDBC credentials, DB passwords)
# from the master VLC_DEV_PASSWORD in .env. Run this after cloning or
# whenever .env changes.
#
# Usage:
#   ./scripts/sync-dev-secrets.sh
#
set -euo pipefail
cd "$(dirname "$0")/.."

log() { echo "[secrets] $*"; }
err() { echo "[secrets] ERROR: $*" >&2; exit 1; }

# --- Validating .env exists ---
if [ ! -f .env ]; then
  err ".env file not found. Copy .env.example to .env and set VLC_DEV_PASSWORD."
fi

# --- Loading .env ---
log "Loading .env ..."
set -a
# shellcheck disable=SC1091
. .env
set +a

# --- Validating required variables ---
if [ -z "${VLC_DEV_PASSWORD:-}" ]; then
  err "VLC_DEV_PASSWORD not set in .env"
fi

log "Generating secrets from VLC_DEV_PASSWORD ..."

# --- 1) Nginx Basic Auth ---
log "Creating compose/.htpasswd (nginx basic auth) ..."
mkdir -p compose
printf "admin:%s\n" "$(openssl passwd -apr1 "$VLC_DEV_PASSWORD")" > compose/.htpasswd
chmod 600 compose/.htpasswd

# --- 2) Kafka Connect secrets ---
log "Creating connect/secrets/secrets.properties (JDBC credentials) ..."
mkdir -p connect/secrets
cat > connect/secrets/secrets.properties <<EOF
TS_JDBC_URL=jdbc:postgresql://timescaledb:5432/vlc
TS_USERNAME=vlc_dev
TS_PASSWORD=${VLC_DEV_PASSWORD}
EOF
chmod 600 connect/secrets/secrets.properties

# --- 3) DB password override script (for fresh DB init) ---
log "Creating db/init/020-vlc-password.override.sql (Postgres password) ..."
mkdir -p db/init
cat > db/init/020-vlc-password.override.sql <<EOF
-- Auto-generated by sync-dev-secrets.sh - DO NOT COMMIT
ALTER ROLE vlc_dev WITH PASSWORD '${VLC_DEV_PASSWORD}';
EOF
chmod 600 db/init/020-vlc-password.override.sql

# --- 4) Producer .env (if needed for local testing) ---
if [ -d producer ]; then
  log "Ensuring producer can access Schema Registry ..."
  # Producer reads SCHEMA_REGISTRY_URL from env or defaults to http://schema-registry:8081
fi

log "Done. Generated files:"
log "  - compose/.htpasswd"
log "  - connect/secrets/secrets.properties"
log "  - db/init/020-vlc-password.override.sql"
log ""
log "Next steps:"
log "  1. Start infra: docker compose --profile infra up -d"
log "  2. Bootstrap Kafka: ./scripts/bootstrap_kafka.sh"
log "  3. Deploy connectors: ./scripts/post_connectors.sh deploy"

